"use client";

import "./globals.css";
import { Inter } from "next/font/google";
import Providers from "./providers";
import HeroSection from "../components/HeroSection";
import "./globals.css";
import Navbar from "@/components/Navbar";
import { QueryClient, QueryClientProvider } from "@tanstack/react-query";
import { UserProviders } from "@/providers/UserProviders";

const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  // Create a client
  const queryClient = new QueryClient();
  return (
    <html lang="en">
      <body className={inter.className}>
        <UserProviders>
          <QueryClientProvider client={queryClient}>
            <Providers>{children}</Providers>
          </QueryClientProvider>
        </UserProviders>
      </body>
    </html>
  );
}
